### ISSUE TITLE
quill login fails

### ISSUE THREAD

**Issue by pgte** [opsmezzo/quill#20]
quill-cli@0.2.2-1

``` sh
$ quill login
info:    Welcome to quill
info:    It worked if it ends with quill ok
info:    Executing command login

/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/node_modules/read/lib/read.js:15
    throw new Error('default value must be string or number')
          ^
Error: default value must be string or number
    at read (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/node_modules/read/lib/read.js:15:11)
    at EventEmitter.prompt.getInput (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:465:3)
    at get (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:322:12)
    at prompt.get (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:281:7)
    at async.forEachSeries.iterate (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:108:13)
    at Object.async.forEachSeries (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:124:9)
    at iterate (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:280:11)
    at EventEmitter.prompt.get (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:321:3)
    at setupAuth (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron-cli-users/lib/commands.js:204:16)
    at exports.login (/usr/local/lib/node_modules/quill-cli/node_modules/flatiron-cli-users/lib/commands.js:251:3)
```

**Comment by mmalecki** [comment]
Fixed. Please make sure you update `flatiron` in your `quill` installation, Pedro.
