### ISSUE TITLE
Error: Too many versions installed: 2

### ISSUE THREAD

**Issue by jcrugzz** [opsmezzo/quill#90]
This case seems to occur after installing a new `quill` with `npm i -g quill-cli`.

Running `quill configure`

``` sh
error:   Too many versions installed: 2
error:   Error: Too many versions installed: 2
error:       at readVersion (/opt/local/lib/node_modules/quill-cli/lib/quill/composer/installed.js:252:23)
error:       at async.iterator.fn (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/async/lib/async.js:517:34)
error:       at async.waterfall.wrapIterator (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/async/lib/async.js:441:34)
error:       at process.startup.processNextTick.process._tickCallback (node.js:244:9)
info:    quill not ok
```

Thoughts @mmalecki?

**Comment by mmalecki** [comment]
This started happening with `npm-manager`, but I'm not sure what's the reason here.
