### ISSUE TITLE
Odd flatiron error

### ISSUE THREAD

**Issue by jcrugzz** [opsmezzo/quill#91]
Encountered this one after uninstalling and then reinstalling `quill-cli`.

``` bash
TypeError: Cannot read property 'capitalize' of undefined
    at Object.<anonymous> (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/prompt/lib/prompt.js:12:31)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at exports.prompt (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron/lib/flatiron/plugins/cli.js:415:20)
    at cliUsers.attach (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron-cli-users/lib/flatiron-cli-users.js:54:6)
    at App.use (/opt/local/lib/node_modules/quill-cli/node_modules/flatiron/node_modules/broadway/lib/broadway/app.js:165:31)
```

Any ideas? @indexzero @mmalecki

**Comment by jcrugzz** [comment]
This was a bug in `prompt` fixed in flatiron bump in 0cbf56d915ae4134ddf8cb680d120f5819c4b095
